name: Test Install

on: [push]

jobs:
  build:
    name: '${{ matrix.os }} - Py${{ matrix.python-version }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [2.7, 3.6, 3.7, 3.8]
      exclude:
        - os: macos-latest
          python-version: 2.7
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install snowmicrotoolset
      run: |
        pip install .
    - name: Test import
      run: |
        python -c "from __future__ import print_function; import snowmicrotoolset; print(snowmicrotoolset.__version__); import sys; print(sys.version_info)"